### ISSUE TITLE
screen gets too dim

### ISSUE THREAD

**Issue by takiainen** [otaconix/caffeinetile#2]
Caffeinetile works only partly: after 30s my screen turns very very dim, hardly readable, but still remains on. This happens when caffeine is activated. Without it the screen just turns off as expected. I think this dimming of the screen beyond usable is not intented, maybe a bug?

I'm running in on android 7,Slim7, One plus One

**Comment by otaconix** [comment]
Hi there. It's not exactly a bug, but I can see how you might think it is.

The way caffeinetile works is by asking Android to keep the screen on. There are actually two options when doing that: allow the screen to dim, or keep it on full tilt.

I'll see if I can make this behavior configurable.

**Comment by takiainen** [comment]
Oh that was a quick answer. I've used the build-in caffeine tile on some ROM that had it, and there the screen maintained the same brightness during the whole "coffee break". I really enjoy this option, but if the screen dims, I find it the same as if I wasn't using caffeine from the usability's point of view 

Thanks for looking into it!

**Comment by otaconix** [comment]
I've just pushed a new tag (1.3), which should get built by F-Droid within a few days. When that update hits your phone, you should get into the preferences screen of Caffeine Tile by tapping and holding the tile. There you'll find a new toggle, which, by default, is on, which means the screen is allowed to dim.

Let me know how it works out!

**Comment by otaconix** [comment]
The update has been built on F-Droid, so I'm going ahead and closing this issue. Feel free to reopen if necessary!

**Comment by takiainen** [comment]
It's working beautifully, thanks! 

Only thing I'm wondering if users realize the existence of this "hidden" settings menu?
