### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by fknfilewalker** [otaconix/caffeinetile#3]
Hi, really cool widget. Maybe you can add some custom time settings.

Like, 
first press -> 5 min
second press -> unlimited 
third -> off

But also keep the mode you have right now.

**Comment by otaconix** [comment]
I'm guessing you want the same functionality we used to have in CM13, correct? I'll see what I can do.

**Comment by takiainen** [comment]
Maybe make this user selectable behavior via settings toggle? I currently like the simplicity: you just press the tile once and screen remains long as long as needed.
